server:
  port: 8080

grpc:
  server:
    port: ${GRPC_SERVER_PORT:59091}

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.telemetry.collector.config.AvroSerializer