spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

aggregator:
  kafka:
    group-id: aggregator-group
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1