spring:
  main:
    banner-mode: console
    log-startup-info: true

logging:
  level:
    root: INFO
    ru.yandex.practicum: INFO
    org.springframework: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/